version: '3.8'

services:
  smart-stack:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/app/src
      - ./smart-trade.py:/app/smart-trade.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s