"""add screening candidate status

Revision ID: 7863bff8e4e1
Revises: 8adceaabb250
Create Date: 2026-07-21 23:59:35.699924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7863bff8e4e1'
down_revision: Union[str, Sequence[str], None] = '8adceaabb250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_candidates', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('status')

    # ### end Alembic commands ###