"""performance metrics

Revision ID: 93a1c9bba1bc
Revises: cab00d96dbf7
Create Date: 2026-07-23 00:10:05.572594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a1c9bba1bc'
down_revision: Union[str, Sequence[str], None] = 'cab00d96dbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_batches',
    sa.Column('calculation_version', sa.String(length=32), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_evaluation_runs',
    sa.Column('candidate_model_id', sa.String(length=32), nullable=False),
    sa.Column('baseline_model_id', sa.String(length=32), nullable=False),
    sa.Column('folds_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_previews',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('research_case_id', sa.String(length=32), nullable=True),
    sa.Column('decision_entry_id', sa.String(length=32), nullable=True),
    sa.Column('quote_price', sa.Float(), nullable=True),
    sa.Column('quote_ts', sa.DateTime(), nullable=True),
    sa.Column('fee_estimate', sa.Float(), nullable=True),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_previews_account_id'), ['account_id'], unique=False)

    op.create_table('model_promotion_decisions',
    sa.Column('evaluation_run_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_model_id', sa.String(length=32), nullable=False),
    sa.Column('baseline_model_id', sa.String(length=32), nullable=False),
    sa.Column('gate_decisions_json', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['model_evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_metrics',
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('dimension_key', sa.String(length=32), nullable=False),
    sa.Column('dimension_value', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('numerator', sa.Float(), nullable=True),
    sa.Column('denominator', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['metric_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'scope', 'scope_id', 'metric_name', 'dimension_key', name='uq_metric_identity')
    )
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_metrics_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_batch_id'))

    op.drop_table('performance_metrics')
    op.drop_table('model_promotion_decisions')
    with op.batch_alter_table('order_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_previews_account_id'))

    op.drop_table('order_previews')
    op.drop_table('model_evaluation_runs')
    op.drop_table('metric_batches')
    # ### end Alembic commands ###