"""reliable operations

Revision ID: cab00d96dbf7
Revises: f53049210396
Create Date: 2026-07-22 23:55:03.006656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab00d96dbf7'
down_revision: Union[str, Sequence[str], None] = 'f53049210396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_reservations',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('cash_amount', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'state', name='uq_reservation_order_active')
    )
    with op.batch_alter_table('order_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_reservations_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_reservations_order_id'), ['order_id'], unique=False)

    op.create_table('settlement_lots',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trade_id', sa.String(length=32), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=False),
    sa.Column('sellable_on', sa.Date(), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_lots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_lots_sellable_on'), ['sellable_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_lots_symbol'), ['symbol'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_cash', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_case_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('decision_entry_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('quote_snapshot_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_research_case_id'), ['research_case_id'], unique=False)
        batch_op.create_unique_constraint('uq_orders_idempotency_key', ['idempotency_key'])
        batch_op.create_foreign_key('fk_orders_quote_snapshot', 'market_snapshots', ['quote_snapshot_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_orders_decision_entry', 'decision_entries', ['decision_entry_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_orders_research_case', 'research_cases', ['research_case_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_qty', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('reserved_qty')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_quote_snapshot', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_decision_entry', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_research_case', type_='foreignkey')
        batch_op.drop_constraint('uq_orders_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_orders_research_case_id'))
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('quote_snapshot_id')
        batch_op.drop_column('decision_entry_id')
        batch_op.drop_column('research_case_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('reserved_cash')

    with op.batch_alter_table('settlement_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_lots_symbol'))
        batch_op.drop_index(batch_op.f('ix_settlement_lots_sellable_on'))
        batch_op.drop_index(batch_op.f('ix_settlement_lots_account_id'))

    op.drop_table('settlement_lots')
    with op.batch_alter_table('order_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_reservations_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_reservations_account_id'))

    op.drop_table('order_reservations')
    # ### end Alembic commands ###