"""forecast foundation baseline

Revision ID: 8adceaabb250
Revises: 
Create Date: 2026-07-21 23:26:27.059065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adceaabb250'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('equity_curve_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_strategy_name'), ['strategy_name'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_snapshot_symbol_ts', ['symbol', 'ts'], unique=False)

    op.create_table('model_versions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=64), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('training_cutoff', sa.Date(), nullable=True),
    sa.Column('code_revision', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_table('signals',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)

    op.create_table('trading_calendar',
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date', name='uq_calendar_session_date')
    )
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_calendar_session_date'), ['session_date'], unique=False)

    op.create_table('universe_snapshots',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('index_code', sa.String(length=32), nullable=False),
    sa.Column('members_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date', 'index_code', name='uq_universe_date_index')
    )
    with op.batch_alter_table('universe_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universe_snapshots_business_date'), ['business_date'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_run_id'), ['run_id'], unique=False)

    op.create_table('market_data_batches',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('cutoff_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('failures_json', sa.Text(), nullable=True),
    sa.Column('universe_snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['universe_snapshot_id'], ['universe_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date', 'source', name='uq_batch_date_source')
    )
    with op.batch_alter_table('market_data_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_data_batches_business_date'), ['business_date'], unique=False)

    op.create_table('orders',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('filled_qty', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    op.create_table('positions',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_position_account_symbol')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('risk_rules',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('max_position_pct', sa.Float(), nullable=False),
    sa.Column('max_single_pct', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('take_profit_pct', sa.Float(), nullable=False),
    sa.Column('max_daily_trades', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_rules_account_id'), ['account_id'], unique=True)

    op.create_table('daily_bars',
    sa.Column('market_data_batch_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('adj_factor', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['market_data_batch_id'], ['market_data_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_data_batch_id', 'symbol', 'date', name='uq_dailybar_batch_symbol_date')
    )
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_bars_market_data_batch_id'), ['market_data_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_bars_symbol'), ['symbol'], unique=False)

    op.create_table('prediction_snapshots',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=False),
    sa.Column('market_data_batch_id', sa.String(length=32), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('p_up', sa.Float(), nullable=False),
    sa.Column('p_flat', sa.Float(), nullable=False),
    sa.Column('p_down', sa.Float(), nullable=False),
    sa.Column('median_return', sa.Float(), nullable=False),
    sa.Column('lower_return', sa.Float(), nullable=False),
    sa.Column('upper_return', sa.Float(), nullable=False),
    sa.Column('expected_excess_return', sa.Float(), nullable=False),
    sa.Column('expected_mfe', sa.Float(), nullable=False),
    sa.Column('expected_mae', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_data_batch_id'], ['market_data_batches.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date', 'symbol', 'model_version_id', 'horizon_days', name='uq_prediction_date_symbol_model_horizon')
    )
    with op.batch_alter_table('prediction_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_snapshots_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_snapshots_symbol'), ['symbol'], unique=False)

    op.create_table('screening_runs',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=False),
    sa.Column('market_data_batch_id', sa.String(length=32), nullable=True),
    sa.Column('universe_snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_data_batch_id'], ['market_data_batches.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['universe_snapshot_id'], ['universe_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date', 'model_version_id', name='uq_screening_date_model')
    )
    with op.batch_alter_table('screening_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_runs_business_date'), ['business_date'], unique=False)

    op.create_table('trades',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('stamp_duty', sa.Float(), nullable=False),
    sa.Column('transfer_fee', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_filled_at'), ['filled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)

    op.create_table('review_results',
    sa.Column('prediction_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('benchmark_excess', sa.Float(), nullable=True),
    sa.Column('signed_error', sa.Float(), nullable=True),
    sa.Column('interval_coverage', sa.Boolean(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('direction_correct', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_snapshot_id'], ['prediction_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_snapshot_id', name='uq_review_prediction')
    )
    with op.batch_alter_table('review_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_results_prediction_snapshot_id'), ['prediction_snapshot_id'], unique=False)

    op.create_table('screening_candidates',
    sa.Column('screening_run_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('prediction_snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_snapshot_id'], ['prediction_snapshots.id'], ),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_run_id', 'symbol', name='uq_candidate_run_symbol')
    )
    with op.batch_alter_table('screening_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_candidates_screening_run_id'), ['screening_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_candidates_screening_run_id'))

    op.drop_table('screening_candidates')
    with op.batch_alter_table('review_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_results_prediction_snapshot_id'))

    op.drop_table('review_results')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_order_id'))
        batch_op.drop_index(batch_op.f('ix_trades_filled_at'))
        batch_op.drop_index(batch_op.f('ix_trades_account_id'))

    op.drop_table('trades')
    with op.batch_alter_table('screening_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_runs_business_date'))

    op.drop_table('screening_runs')
    with op.batch_alter_table('prediction_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_prediction_snapshots_business_date'))

    op.drop_table('prediction_snapshots')
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_bars_symbol'))
        batch_op.drop_index(batch_op.f('ix_daily_bars_market_data_batch_id'))

    op.drop_table('daily_bars')
    with op.batch_alter_table('risk_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_rules_account_id'))

    op.drop_table('risk_rules')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_account_id'))

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_account_id'))

    op.drop_table('orders')
    with op.batch_alter_table('market_data_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_batches_business_date'))

    op.drop_table('market_data_batches')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_run_id'))

    op.drop_table('backtest_trades')
    with op.batch_alter_table('universe_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universe_snapshots_business_date'))

    op.drop_table('universe_snapshots')
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_calendar_session_date'))

    op.drop_table('trading_calendar')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_source'))
        batch_op.drop_index(batch_op.f('ix_signals_created_at'))

    op.drop_table('signals')
    op.drop_table('model_versions')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_symbol_ts')
        batch_op.drop_index(batch_op.f('ix_market_snapshots_symbol'))

    op.drop_table('market_snapshots')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_strategy_name'))

    op.drop_table('backtest_runs')
    op.drop_table('accounts')
    # ### end Alembic commands ###