"""research loop

Revision ID: f53049210396
Revises: 7863bff8e4e1
Create Date: 2026-07-22 00:58:54.772620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53049210396'
down_revision: Union[str, Sequence[str], None] = '7863bff8e4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_cases',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('prediction_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('screening_candidate_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('initial_direction', sa.String(length=16), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('expected_return_lower', sa.Float(), nullable=False),
    sa.Column('expected_return_upper', sa.Float(), nullable=False),
    sa.Column('counterargument', sa.Text(), nullable=False),
    sa.Column('invalidation_condition', sa.Text(), nullable=False),
    sa.Column('planned_entry', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('frozen_analysis_json', sa.Text(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_snapshot_id'], ['prediction_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screening_candidate_id'], ['screening_candidates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_cases_prediction_snapshot_id'), ['prediction_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_cases_symbol'), ['symbol'], unique=False)

    op.create_table('decision_entries',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('research_case_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['decision_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_entries_research_case_id'), ['research_case_id'], unique=False)

    op.create_table('evidence_entries',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('research_case_id', sa.String(length=32), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_label', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_entries_research_case_id'), ['research_case_id'], unique=False)

    op.create_table('review_notes',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('research_case_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attribution_json', sa.Text(), nullable=True),
    sa.Column('error_tags_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_notes_research_case_id'), ['research_case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_notes_research_case_id'))

    op.drop_table('review_notes')
    with op.batch_alter_table('evidence_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_entries_research_case_id'))

    op.drop_table('evidence_entries')
    with op.batch_alter_table('decision_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_entries_research_case_id'))

    op.drop_table('decision_entries')
    with op.batch_alter_table('research_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_cases_symbol'))
        batch_op.drop_index(batch_op.f('ix_research_cases_prediction_snapshot_id'))

    op.drop_table('research_cases')
    # ### end Alembic commands ###